### ISSUE TITLE
Verify Freebay is accessible on freebay.fre.ag

### ISSUE THREAD

**Issue by hamish-deas** [fac/freebay#125]
Raised by Ops:

The freebay.bargains domain name is going to expire soon. It's currently with a different registrar (iwantmyname.com) to our usual one (DNSimple) so ideally we'd transfer it so they're all in the same place, but unfortunately DNSimple doesn't support the .bargains TLD. We were thinking of creating a new hostname for it to keep them all together, in fact it'd be even simpler if we handled internal apps as subdomains under the same domain name.

We already own freeagent.io, so how about freebay.freeagent.io, or we could go with a subdomain of fre.ag instead? Do you have any preferences on domain name or is one of those fine?
...
Spoke to Nathan and he's got permission, so all sorted there and I can get it responding to freebay.fre.ag now

Verification needed that Freebay is accessible on freebay.fre.ag

**Comment by dmorgan-fa** [comment]
Looks to be working now: https://freebay.fre.ag
